### ISSUE TITLE
init

### ISSUE THREAD

**Issue by trov4** [KSU-IEEE/noise-recognition#1]
@jhalimro create the new branch `1-init` and be sure to put any updates/important links you have here

**Comment by trov4** [comment]
Goal for first meeting:  
Have a method determined for this. Not necessarily implemented, just picked.

**Comment by trov4** [comment]
@jhalimro : 
- Paste notes into issue 
- Create an Arduino Library -- Trevor send resources

**Comment by trov4** [comment]
Arduino/libraries 
- FFT_library (actual name)
     - pull from github
- library 
     - noise_detector.h (define class main functions capture_audio() perform_fft() my_object.control() )
    #include fft_library/library_name 
     - noise_detector.cpp 

Think about sequential logic--how will my class operate

**Comment by jhalimro** [comment]
Implementing Voice Control via Audio Frequency Detector for Arduino

Context: In the competition arena, there will be two designated areas that the power pellet will be located in, area A or area B. The audio frequency detector will be used to detect the presence of a frequency, or lack thereof, before sending a signal to the motor to travel to the preset destination. This approach will take into account of whether or not verbal/wireless internet communication is prohibited.

Cost: $14 for Sound Detection Module

Necessary Libraries (To be extended if necessary): #include "arduinoFFT.h"

The FFT algorithm enables you to see which frequencies are present in any analog signal and also see which of those frequencies that are the most dominating.

The term bins is related to the result of the FFT, where every element in the result array is a bin. One can say this is the “resolution” of the FFT. Every bin represent a frequency interval, just like a histogram. The number of bins you get is half the amount of samples spanning the frequency range from zero to half the sampling rate.

Baud rate is the number of symbol changes, waveform changes, or signaling events across the transmission medium per unit of time
```
/*
 File/Sketch Name: AudioFrequencyDetector

 Version No.: v1.0 Created 12 December, 2019
 
 Original Author: Clyde A. Lettsome, PhD, PE, MEM
 
 Description:  This code/sketch makes displays the approximate frequency of the loudest sound detected by a sound detection module. For this project, the analog output from the 
 sound module detector sends the analog audio signal detected to A0 of the Arduino Uno. The analog signal is sampled and quantized (digitized). A Fast Fourier Transform (FFT) is
 then performed on the digitized data. The FFT converts the digital data from the approximate discrete-time domain result. The maximum frequency of the approximate discrete-time
 domain result is then determined and displayed via the Arduino IDE Serial Monitor.

 Note: The arduinoFFT.h library needs to be added to the Arduino IDE before compiling and uploading this script/sketch to an Arduino.

 License: This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License (GPL) version 3, or any later
 version of your choice, as published by the Free Software Foundation.

 Notes: Copyright (c) 2019 by C. A. Lettsome Services, LLC
 For more information visit https://clydelettsome.com/blog/2019/12/18/my-weekend-project-audio-frequency-detector-using-an-arduino/

*/

#include "arduinoFFT.h"
 
#define SAMPLES 128             //SAMPLES-pt FFT. Must be a base 2 number. Max 128 for Arduino Uno.
#define SAMPLING_FREQUENCY 2048 //Ts = Based on Nyquist, must be 2 times the highest expected frequency.
 
arduinoFFT FFT = arduinoFFT();
 
unsigned int samplingPeriod;
unsigned long microSeconds;
 
double vReal[SAMPLES]; //create vector of size SAMPLES to hold real values
double vImag[SAMPLES]; //create vector of size SAMPLES to hold imaginary values
 
void setup() 
{
    Serial.begin(115200); //Baud rate for the Serial Monitor
    samplingPeriod = round(1000000*(1.0/SAMPLING_FREQUENCY)); //Period in microseconds 
}
 
void loop() 
{  
    /*Sample SAMPLES times*/
    for(int i=0; i<SAMPLES; i++)
    {
        microSeconds = micros();    //Returns the number of microseconds since the Arduino board began running the current script. 
     
        vReal[i] = analogRead(0); //Reads the value from analog pin 0 (A0), quantize it and save it as a real term.
        vImag[i] = 0; //Makes imaginary term 0 always

        /*remaining wait time between samples if necessary*/
        while(micros() < (microSeconds + samplingPeriod))
        {
          //do nothing
        }
    }
 
    /*Perform FFT on samples*/
    FFT.Windowing(vReal, SAMPLES, FFT_WIN_TYP_HAMMING, FFT_FORWARD);
    FFT.Compute(vReal, vImag, SAMPLES, FFT_FORWARD);
    FFT.ComplexToMagnitude(vReal, vImag, SAMPLES);

    /*Find peak frequency and print peak*/
    double peak = FFT.MajorPeak(vReal, SAMPLES, SAMPLING_FREQUENCY);

    /*Here is where modifications will come in. If the frequency is above a certain threshold or exists as a value greater than 0/null, then tell robot to go to area A, other wise traverse to area b*/
    Serial.println(peak);     //Print out the most dominant frequency.
 
    /*Script stops here. Hardware reset required.*/
    while (1); //do one time
}

**Comment by trov4** [comment]
Library with functions:
- getSample() 
- performFFT()  
- has_freq(int freq)  

member items:
arduinoFFT FFT = arduinoFFT();  
samplingPeriod 
double vReal[SAMPLES]; //create vector of size SAMPLES to hold real values
double vImag[SAMPLES]; //create vector of size SAMPLES to hold imaginary values

### Feb 3rd:  
- convert that arduino library to function

Arduino libraries:
1.) create the folder /path/to/Arduino/lib/targets/libraries/noise-recognition 
2.) create the files:
```
noise-recognition.h
noise-recognition.cpp
```
3.) Create Arduino file that has the line 
`# include <noise-recognition/noise-recognition.h>`

### after Feb 3rd:  
- commit on to github 

@jhalimro
